package org.dsa.core.prepare

/**
  * Created by xubo on 2016/12/27.
  */
object test {
  def main(args: Array[String]) {
    val arrLength = 5
    var flag = new Array[Boolean](arrLength)

    for (i <- 0 until (arrLength)) {
      println(flag(i))
      flag(i) = true
    }

    flag.foreach(println)
    println(60 / 50)
    println(40 / 50)
    println(25 / 50)
    println((40 + 25) / 50)

    val intervalValue = 50
    println((1701 + intervalValue / 2) / intervalValue)
    println((1700 + intervalValue / 2) / intervalValue)
    println(1700 % intervalValue == 0)
    println(1701 % intervalValue == 0)
    println("MELSCSEVPLYGQRTVYAKFGKNVYLPEDAEFYFIYDGSHQRHVVIADRVEDNVLQSIIPGHWLQETVMVSVCLCSEGYSPVTMGSGSVTYVDNMACRLARLLVTQADRLTPCSHQTLLTPFALTAEALPALDEELVLALTQLELPLGWTVLGNSSLEVCLHRESLLHLAVRWALPKLFHFLLCLPGGVKALELPNEEATTPLDLALHGGHSMLVEDISNFQGRRSPGFSRLRLNEDATLQFDRSSETLTLTVNHTAEHLLEADIKLFRKYFWDRAFLVKALDQEAKTERATMPSGAAETEEEVRNLESGRSPSEEEEDGQLVKSQADGPSEQEDQDRLVLDHSFDGLKKSKHAPASLAAGQLSDVPNGGDEVYANCMVIDQVGDLDINYINIEGLSTHTSPESMRSTLGPQACKHILPPDTSPCGHLLCEDSDRTLDAAASQSCMSPPSSHTSNLNLSFGLHGFVKEQSHLKKRSSSLDALVADSEEEGRSEPPICYAVGSQSSPRTGLPGGDELDSFDANTEPDCNISRTESLSLSSTLHSKESLLSGIRSRSYSCSSPKISSGKSRLVRDFTVCSSSEEQRSYSFQEPPGEKRIQEEEWDDYIIPAKAESEKHKVSRTFSFLMNRMTSPRNKSKMKNKDTKDKEKLNRHQFVPGTFSGVLQCSGCDKTLLGKESLQCANCKANTHKGCKDTVPPCTKKFQDKYNKNKPQTILGSSSVRDVPPPGLSLHPSPSMPIGLPAGRKETAGQAHPLSRSVPGTTLESFRRAVTSLESEGDSNSWRSRSHSDELFQSMGSSPSTESFMMEDVVDSSLWSELSSDAQEFEAESWSLVVDPSFCSRQEKDVIKRQDVIFELMQTEVHHIQTLLIMSEVFRKGMKEELQLDHSTVDRIFPCLDELLETHKHFFFSMKERRQESCTGNDRNFVINQIGDILVQQFSEENASKMKRIYGDFCSHHKEAMSLFKELQQNKKFQNFIKIRNSNLLARRRGIPECILLVTQRITKYPVLVERILQYTKERTEEHRDLCRALGLIKDMIAAVDLKVSEYEKNQKWLEILNKIENKTYTKLKNGHVFRKQALMSQERALLHDGLVYWKTATGRFKDILALLLTDVLLFLQEKDQKYIFAAVDQKPSVISLQKLIAREVANEERGMFLISASSAGPEMYEIHTSSKEERNNWMRRIQQAVESCPEEEGGRTSESDEERRKADARVAKIQQCQEILSNQDQQICTYLEEKLHIYAELGELSGFEDVHLEPHLLIKPDPGEPPQAASLLAAALREAESLQVAVKASKLADVSQPSEEGPGGAVLADTLSAQDAPASPTAFTEGTEGRGCWDVDPRLQGVVTDLAVSDAGEKVEYRSFSGSSQSEIIQAIQNLTRLLYSLQAALTIQDSHIEIHKLVLQQQESLAPSHSFRGGPLQDQEKSRYLEKHREELANIHKLQYQFQQEQRRWHRTCDQQQREQEAQESWLQARERECQSQEELLLRHRSELDHQLQEYQQNLERLREGQRMVERERQRMRDQQGLLGHCKHSRQRSLPAVFSPGSKEVTELNRAESLCHEKSFFLNDAFTHMSLNTSNKPNPSGAPWDAHPPGGSHLDLARTSDSQIEVKMDVSQPSDVNSELWTTGLGPQRPARQESIKDSCKNVADLNSFQTESPDPQDSNQRGPQPQTLITEAKLTPPMAAGHGGDAGDGAEENIVYL".length)
    val arrStr = new Array[String](3)
    arrStr.foreach(println)

  }
}
